ARG ALPINE_VERSION=3.23.3
ARG ALPINE_IMAGE_DIGEST=sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
FROM alpine:${ALPINE_VERSION}@${ALPINE_IMAGE_DIGEST}

RUN apk add --no-cache \
        binutils \
        build-base \
        bzip2 \
        ca-certificates \
        curl \
        file \
        linux-headers \
        make \
        musl-dev \
        patch \
        perl

WORKDIR /workspace
